pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Nova"
include(":app")

// --- Android SDK discovery ---------------------------------------------------
// AGP will only take the SDK path from local.properties or ANDROID_HOME/
// ANDROID_SDK_ROOT. local.properties is machine-local and git-ignored, so a
// fresh clone has neither and the build dies with "SDK location not found"
// before it compiles anything. Android Studio papers over this by writing the
// file itself on first open, which is why Run works there while `./gradlew`
// does not - and why the gap only ever bites the person building from a
// terminal. Closed here rather than in the README: an instruction someone has
// to read and follow is a step that can be skipped, and this one cannot fail
// safely. If the SDK sits where the platform's own installer puts it, point at
// it and carry on; if it is somewhere else, say what to set and why.
run {
    val localProperties = java.io.File(rootDir, "local.properties")
    val alreadyDeclared = localProperties.exists() && java.util.Properties()
        .apply { localProperties.inputStream().use { load(it) } }
        .getProperty("sdk.dir") != null
    val fromEnvironment = sequenceOf("ANDROID_HOME", "ANDROID_SDK_ROOT")
        .mapNotNull(System::getenv).any(String::isNotBlank)
    if (alreadyDeclared || fromEnvironment) return@run

    val home = java.io.File(System.getProperty("user.home"))
    val osName = System.getProperty("os.name").lowercase()
    val candidates = when {
        osName.startsWith("windows") -> listOf(
            // Forward slashes throughout: java.io.File normalises them on Windows,
            // and they keep this off Kotlin's escape-sequence rules.
            java.io.File(System.getenv("LOCALAPPDATA") ?: "$home/AppData/Local", "Android/Sdk"))
        osName.startsWith("mac") -> listOf(java.io.File(home, "Library/Android/sdk"))
        else -> listOf(java.io.File(home, "Android/Sdk"), java.io.File(home, "android-sdk"))
    }
    // platform-tools rather than the directory itself: an SDK folder that exists
    // but holds nothing is what a half-finished Studio install leaves behind,
    // and pointing AGP at one fails later and far less legibly than failing here.
    val sdk = candidates.firstOrNull { java.io.File(it, "platform-tools").isDirectory }
        ?: error(
            "No Android SDK found. Looked in: " +
            candidates.joinToString { it.path } + "\n" +
            "Install it (Android Studio > SDK Manager, or the standalone " +
            "command-line tools), then either let Studio open this project once " +
            "or set ANDROID_HOME to the SDK directory."
        )

    // Properties.store, not writeText: sdk.dir is Java .properties syntax, where
    // a Windows path's backslashes and drive colon have to be escaped. Getting
    // that wrong yields "Invalid file path" rather than anything diagnostic.
    java.util.Properties().apply { setProperty("sdk.dir", sdk.absolutePath) }
        .store(
            localProperties.writer(),
            "Generated by settings.gradle.kts because no SDK location was configured.\n" +
            "Machine-local and git-ignored; Android Studio rewrites it when it opens the project."
        )
    println("[nova] wrote local.properties -> sdk.dir=${sdk.absolutePath}")
}
