"""Data structures for the notes store.

A Note is something the user wrote down, dictated, or captured. Unlike an
Episode it is theirs to edit and delete, and unlike a Persona Fact it is not a
belief about them: a lecture capture is the lecturer's words, and a quick note
("parked on level 3") stops mattering by tomorrow. Neither is ever read by
consolidation. A note only reaches Persona when the user explicitly promotes
it, and then the fact carries `note_id` so deleting either end sticks.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field

Source = Literal["device_voice", "phone_voice", "typed", "assistant"]
Kind = Literal["quick", "dictation", "capture"]
SummaryStatus = Literal["none", "pending", "done", "stale", "failed"]
SummariseMode = Literal["auto", "never"]


class NoteSegment(BaseModel):
    """One stretch of a transcript, with where it sits in the recording.
    Captures arrive as many of these; a quick note has none."""

    start_s: float
    end_s: float
    text: str


class NoteContext(BaseModel):
    """What was going on when the note was taken - lets the list say
    'COMP2100 Lecture' rather than just a time."""

    calendar_title: Optional[str] = None
    location: Optional[str] = None


class NoteStt(BaseModel):
    """How the text was produced, so the UI can say 'may contain errors'."""

    engine: Optional[str] = None
    avg_conf: Optional[float] = None


class FlaggedMoment(BaseModel):
    t_s: float
    quote: str


class NoteSummary(BaseModel):
    """What notes_pipeline/summarise.py produces - also the structured-output
    schema sent to Claude, so every field here is one the model fills."""

    title: str
    tldr: str
    key_points: list[str] = Field(default_factory=list)
    action_items: list[str] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)
    flagged_moments: list[FlaggedMoment] = Field(default_factory=list)


class NoteIn(BaseModel):
    """POST /notes. `id` is generated by the client and doubles as the
    idempotency key: the phone's outbox retries until it gets a 2xx, and a
    retry of a note that did land must not create a second one."""

    id: str
    created_at: Optional[datetime] = None
    source: Source = "typed"
    kind: Kind = "quick"
    title: Optional[str] = None
    text: str
    segments: list[NoteSegment] = Field(default_factory=list)
    duration_s: Optional[float] = None
    context: Optional[NoteContext] = None
    stt: Optional[NoteStt] = None
    tags: list[str] = Field(default_factory=list)
    summarise: SummariseMode = "auto"
    origin_episode_id: Optional[str] = None


class Note(BaseModel):
    """A stored note, as every reader sees it."""

    id: str
    # The owner - set by the store from the verified token, never by a client
    # (NoteIn has no such field). Lets the pipeline process a note as its owner.
    user_id: Optional[str] = None
    created_at: datetime
    updated_at: datetime
    source: Source
    kind: Kind
    title: Optional[str] = None
    text: str
    segments: list[NoteSegment] = Field(default_factory=list)
    duration_s: Optional[float] = None
    context: Optional[NoteContext] = None
    stt: Optional[NoteStt] = None
    tags: list[str] = Field(default_factory=list)
    summary: Optional[NoteSummary] = None
    summary_status: SummaryStatus = "none"
    # For a spoken note: what Nova thinks was meant, beside `text` as heard
    # (notes_pipeline/interpret.py). None until read, or when nothing changed.
    interpreted_text: Optional[str] = None
    origin_episode_id: Optional[str] = None
    promoted_fact_ids: list[str] = Field(default_factory=list)

    def display_title(self) -> str:
        """What a list row or a spoken recall calls this note."""
        if self.title:
            return self.title
        if self.summary and self.summary.title:
            return self.summary.title
        words = self.text.split()
        return " ".join(words[:8]) + ("…" if len(words) > 8 else "")


class NotePatch(BaseModel):
    """PATCH /notes/{id}. Only what the user can edit; None leaves a field alone."""

    title: Optional[str] = None
    text: Optional[str] = None
    tags: Optional[list[str]] = None
    segments: Optional[list[NoteSegment]] = None


class NoteChunkIn(BaseModel):
    """One embedding window over a long note - see notes_pipeline/chunking.py."""

    idx: int
    text: str
    start_s: Optional[float] = None
    end_s: Optional[float] = None


class NoteQuery(BaseModel):
    """notes.search(). All filters optional; no text means newest first."""

    text: Optional[str] = None
    since: Optional[datetime] = None
    until: Optional[datetime] = None
    kind: Optional[Kind] = None
    limit: int = 10


class NoteMatch(BaseModel):
    """A search hit: the note, how well it scored, and the passage that matched
    (the best chunk for a long note) - recall hands the model the snippet, never
    a whole transcript."""

    note: Note
    score: float
    snippet: str
    snippet_start_s: Optional[float] = None


def note_from_row(row: dict[str, Any]) -> Note:
    """A `notes` row (Supabase or in-memory) as a Note."""
    fields = {k: v for k, v in row.items() if k in Note.model_fields and v is not None}
    return Note(**fields)
