package com.example.novav2.state

import android.content.Context
import com.example.novav2.data.NovaDatabase
import com.example.novav2.data.ReminderEntity
import com.example.novav2.model.PlaceEvent
import com.example.novav2.model.ReminderPriority
import com.example.novav2.model.ReminderStatus
import com.example.novav2.model.UserState
import com.example.novav2.service.ReminderSpeechService
import java.time.ZoneId

/**
 * What happens when the reminder alarm goes off:
 *
 *   1. load everything due (within [COALESCE_MILLIS] - Doze rate-limits while-idle alarms, so
 *      one wake-up delivers a group rather than setting another alarm a few seconds out)
 *   2. read the situation - the last UserState if it is fresh, a new snapshot otherwise
 *   3. ask [InterruptionPolicy] for a plan per reminder
 *   4. defer or deliver: one buzz for the whole batch, a notification each (grouped), headphone
 *      speech if the plan says so
 *   5. reconcile, via [ReminderRepository.saveAll]
 *
 * [onPlace] is the same from step 2 on, for place reminders whose geofence just fired - so
 * arriving at the lecture theatre mid-lecture holds the reminder until the lecture ends, exactly
 * as a timed one would be.
 *
 * Everything said at fire time is fixed and written here, never generated by the model - the
 * same rule AmbientCheckRunner follows. There is no model call on this path at all.
 */
object ReminderEngine {
    private const val COALESCE_MILLIS = 60_000L
    private const val FRESH_STATE_MILLIS = 30_000L
    private const val MISSED_AFTER_MILLIS = 5 * 60_000L
    private const val REBUZZ_AFTER_MILLIS = 10 * 60_000L
    /** An every-time place reminder goes off at most this often - walking out to the car park
     * and back in, or a jittery fix at the edge of a geofence, is not a second arrival. */
    private const val PLACE_COOLDOWN_MILLIS = 30 * 60_000L

    suspend fun onAlarm(context: Context) {
        val app = context.applicationContext
        val now = System.currentTimeMillis()
        val zone = ZoneId.systemDefault()
        val dao = NovaDatabase.getInstance(app).reminderDao()

        val toSave = mutableListOf<ReminderEntity>()

        // A recurring reminder delivers its latest due occurrence only - several missed while
        // the phone was off arrive as one. One whose last occurrence went unanswered comes back
        // for the next (superseding it) rather than the ignored one blocking the series.
        val due = dao.scheduledDueBy(now + COALESCE_MILLIS).map { r ->
            if (r.statusEnum == ReminderStatus.PENDING) ReminderTransitions.rollForward(r, now, zone) ?: r else r
        }.toMutableList()
        for (r in dao.recurringFiredDueBy(now + COALESCE_MILLIS)) {
            val next = ReminderTransitions.rollForward(r, now, zone)
            if (next != null) due += next else toSave += ReminderTransitions.armNext(r, now, zone)
        }
        val rebuzz = dao.rebuzzDueBy(now + COALESCE_MILLIS).filter { old -> due.none { it.id == old.id } }
        if (due.isEmpty() && rebuzz.isEmpty()) {
            if (toSave.isNotEmpty()) ReminderRepository.saveAll(app, toSave) else ReminderScheduler.reconcile(app)
            return
        }

        deliver(app, due, rebuzz, toSave, now, zone) { titleFor(it, now, zone) }
    }

    /**
     * A geofence fired: [hits] are the (reminder id, circle index) pairs it names. Each armed
     * place reminder among them, for this [event], is delivered - not before its placeAfterLocal,
     * and one that goes off every time only if it hasn't gone off in the last
     * [PLACE_COOLDOWN_MILLIS].
     */
    suspend fun onPlace(context: Context, event: PlaceEvent, hits: List<Pair<String, Int>>) {
        val app = context.applicationContext
        val now = System.currentTimeMillis()
        val zone = ZoneId.systemDefault()
        val byId = hits.groupBy({ it.first }, { it.second })
        val nowLocal = ReminderTime.toLocal(now, zone)
        val due = NovaDatabase.getInstance(app).reminderDao().armedAtPlaces()
            .filter { it.id in byId && it.place?.on == event }
            // "When I get to uni tomorrow": getting there today doesn't count.
            .filter { r -> r.placeAfterLocal?.let { ReminderTime.parseLocal(it, zone) }?.isAfter(nowLocal) != true }
            .filter { it.statusEnum == ReminderStatus.PENDING || now - (it.firedAtMillis ?: 0L) >= PLACE_COOLDOWN_MILLIS }
            .map { if (it.statusEnum == ReminderStatus.PENDING) it else ReminderTransitions.rearm(it, now) }
        if (due.isEmpty()) return
        val pointNames = due.associate { r ->
            r.id to byId[r.id]?.firstOrNull()?.let { r.place?.points?.getOrNull(it)?.name }
        }
        deliver(app, due, emptyList(), mutableListOf(), now, zone) { placeTitle(it, pointNames[it.id]) }
    }

    /** "At the shops" / "Leaving work" - and for a chain, which branch: "At Woolworths
     * (Woolworths Hawker)". */
    fun placeTitle(r: ReminderEntity, pointName: String?): String {
        val place = r.place ?: return "Reminder"
        val label = place.label.ifBlank { pointName ?: "a place" }
        val where = if (pointName != null && place.points.size > 1 && !pointName.equals(label, ignoreCase = true)) {
            "$label ($pointName)"
        } else label
        return when (place.on) {
            PlaceEvent.ARRIVE -> "At $where"
            PlaceEvent.LEAVE -> "Leaving $where"
        }
    }

    /** Steps 2-5 of the class comment, for reminders already found due. */
    private suspend fun deliver(
        app: Context,
        due: List<ReminderEntity>,
        rebuzz: List<ReminderEntity>,
        toSave: MutableList<ReminderEntity>,
        now: Long,
        zone: ZoneId,
        title: (ReminderEntity) -> String,
    ) {
        val state = freshState(app, now)
        val policyContext = InterruptionPolicy.Context(
            nowMillis = now,
            zone = zone,
            callState = state.callState,
            dnd = state.dnd,
            interruptionFilter = state.interruptionFilter,
            activity = state.activity ?: state.motion,
            currentEvent = InterruptionPolicy.committedEventNow(state.currentEvents, now),
            headsetConnected = state.wiredHeadsetConnected == true || state.bluetoothAudioConnected == true,
            speakWithHeadphones = ReminderPreferences.speakWithHeadphones(app),
        )

        val deliveries = mutableListOf<ReminderNotifier.Delivery>()
        val spoken = mutableListOf<String>()
        var anyImportant = false

        for (r in due) {
            val plan = InterruptionPolicy.plan(
                policyContext,
                InterruptionPolicy.Item(r.priorityEnum, r.deferCount, r.firstDeferredAtMillis),
            )
            when (plan) {
                is InterruptionPolicy.Plan.Defer ->
                    toSave += ReminderTransitions.defer(r, plan.untilMillis, plan.reason, now)
                is InterruptionPolicy.Plan.Deliver -> {
                    val important = r.priorityEnum == ReminderPriority.IMPORTANT
                    anyImportant = anyImportant || important
                    deliveries += ReminderNotifier.Delivery(r, title(r), plan.headsUp)
                    if (plan.speak) spoken += "Reminder: ${r.text}"
                    toSave += ReminderTransitions.fire(r, now, if (important) now + REBUZZ_AFTER_MILLIS else null, zone)
                }
            }
        }
        rebuzz.forEach { toSave += ReminderTransitions.rebuzzed(it, now) }

        if (deliveries.isNotEmpty() || rebuzz.isNotEmpty()) {
            val pattern = if (anyImportant || rebuzz.isNotEmpty()) DeviceCue.Pattern.REMINDER_IMPORTANT
            else DeviceCue.Pattern.REMINDER
            DeviceCue.play(pattern)
        }
        if (deliveries.isNotEmpty()) {
            ReminderNotifier.notify(app, deliveries, groupLabel(deliveries))
        }
        if (spoken.isNotEmpty()) ReminderSpeechService.speak(app, spoken)

        ReminderRepository.saveAll(app, toSave)
    }

    /** The fixed line above a reminder's text. */
    fun titleFor(r: ReminderEntity, nowMillis: Long, zone: ZoneId): String = when {
        r.statusEnum == ReminderStatus.DEFERRED && r.deferReason == "call" -> "Held during your call"
        r.statusEnum == ReminderStatus.DEFERRED && r.deferReason != null -> "Held during ${r.deferReason}"
        r.statusEnum == ReminderStatus.SNOOZED -> "Reminder (snoozed)"
        nowMillis - r.triggerAtMillis > MISSED_AFTER_MILLIS ->
            "Missed at ${ReminderTime.clock(r.triggerAtMillis, zone)}"
        else -> "Reminder"
    }

    /** "3 reminders from COMP2100 Lecture" when a batch was all held for the same thing. */
    private fun groupLabel(deliveries: List<ReminderNotifier.Delivery>): String? {
        if (deliveries.size < 2) return null
        val reasons = deliveries.map { it.reminder.deferReason }.distinct()
        val reason = reasons.singleOrNull()?.takeIf { it != "call" }
        return if (reason != null) "${deliveries.size} reminders from $reason" else "${deliveries.size} reminders"
    }

    private fun freshState(context: Context, nowMillis: Long): UserState =
        SignalRepository.userState.value?.takeIf { nowMillis - it.timestamp < FRESH_STATE_MILLIS }
            ?: UserStateCollector.snapshot(context)
}
